[package]
name = "seymour"
version = "0.1.0"
authors = ["Liam Schumm <lschumm@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
pbr = "1.0.1"
fastapprox = "0.3.0"
rayon = "1.2.0"